name             'riak-cs'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures riak-cs'
long_description 'Installs/Configures riak-cs'
version          '0.1.0'
